code: products
parentCode: seed_insurances
titles:
  en: Products
  it: Prodotti
pageModel: insurance_home
ownerGroup: free
joinGroups: []
displayedInMenu: true
seo: false
charset: utf-8
status: published
widgets:
  - code: back_to_seed
    config: null
    pos: 0
  - code: search_form
    config: null
    pos: 1
  - code: language_choose
    config: null
    pos: 2
  - code: brand_insurance
    config: null
    pos: 3
  - code: navigation-menu
    config:
      navSpec: code(seed_insurances) + code(products) + code(my_portal)
    pos: 4
  - code: insurance_login
    config: null
    pos: 5
  - code: Breadcrumb
    config: null
    pos: 6
  - code: content_viewer
    config:
      modelId: '109'
      contentId: PRD662
    pos: 7
  - code: content_viewer_list
    config:
      userFilters:
        - categoryCode: products
          attributeFilter: false
          key: category
        - attributeFilter: true
          key: title
      modelId: '107'
      maxElemForItem: '3'
      filters:
        - attributeFilter: false
          key: modified
          order: DESC
      title_it: Prodotti Seed Insurance
      title_en: Seed Insurance Product
      contentType: PRD
    pos: 9
  - code: content_viewer
    config:
      modelId: '104'
      contentId: MPC616
    pos: 10
  - code: footer-insurance
    config: null
    pos: 14
