kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Values.app.name }}-composite-app"
  namespace: {{ .Release.Namespace}}
entandoStatus:
  serverStatuses: {}
  entandoDeploymentPhase: "requested"
spec:
  components:
{{- if .Values.prepareInfrastructure }}
    - kind: "EntandoKeycloakServer"
      metadata:
        name: "{{ .Values.app.name }}-kc"
      spec:
        dbms: postgresql
        isDefault: true
        replicas: 1
    - kind: "EntandoClusterInfrastructure"
      metadata:
        name: "{{ .Values.app.name }}-eci"
      spec:
        dbms: postgresql
        replicas: 1
        isDefault: true
{{- end }}
    - kind: "EntandoApp"
      metadata:
        annotations: {}
        labels: {}
        name: "{{ .Values.app.name }}"
      spec:
        dbms: postgresql
        replicas: {{ .Values.app.replicaCount }}
        customServerImage: "{{ .Values.app.repository }}:{{ .Values.app.tag }}"
        ingressPath: "{{ .Values.app.webContext }}"
