---
# Source: preview/charts/operator/templates/ca-cert-secret.yaml
apiVersion: v1
data:
kind: Secret
metadata:
  name: entando-ca-cert-secret
  namespace: flex
type: Opaque

---
# Source: preview/charts/operator/templates/tls-secret.yaml
apiVersion: v1
data:
  tls.crt: >-

  tls.key: >-

kind: Secret
metadata:
  name: entando-tls-secret
  namespace: flex
type: kubernetes.io/tls

---
# Source: preview/charts/operator/templates/docker-image-info-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: entando-docker-image-info
  namespace: flex
data:
  app-builder: >-
    {"version":"6.1.201","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  busybox: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-avatar-plugin: >-
    {"version":"6.0.5","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-component-manager: >-
    {"version":"6.2.8","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-eap: >-
    {"version":"6.1.124","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-wildfly: >-
    {"version":""6.2.0.rc-10-demo.12,"executable-type":"jvm","registry":"docker.io","organization":"jwhite101"}
  entando-k8s-app-controller: >-
    {"version":"6.2.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-app-plugin-link-controller: >-
    {"version":"6.1.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-cluster-infrastructure-controller: >-
    {"version":"6.2.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-composite-app-controller: >-
    {"version":"6.2.1","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-controller-coordinator: >-
    {"version":"6.2.4","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-dbjob: >-
    {"version":"6.1.4","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-keycloak-controller: >-
    {"version":"6.2.8","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-plugin-controller: >-
    {"version":"6.2.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-service: >-
    {"version":"6.2.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-keycloak: >-
    {"version":"6.1.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-plugin-sidecar: >-
    {"version":"6.0.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-process-driven-plugin: >-
    {"version":"6.0.51","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  mysql-57-centos7: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  postgresql-96-centos7: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"entando"}

---
# Source: preview/charts/operator/templates/k8s-service-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-k8s-service
  namespace: flex

---
# Source: preview/charts/operator/templates/operator-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-operator
  namespace: flex

---
# Source: preview/charts/operator/templates/plugin-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-plugin
  namespace: flex

---
# Source: preview/charts/operator/templates/k8s-service-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-k8s-service
  namespace: flex
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandokeycloakservers
      - entandokeycloakservers/finalizers
      - entandoclusterinfrastructures
      - entandoclusterinfrastructures/finalizers
      - entandoapps
      - entandoapps/finalizers
      - entandoplugins
      - entandoplugins/finalizers
      - entandoapppluginlinks
      - entandoapppluginlinks/finalizers
      - entandodatabaseservices
      - entandodatabaseservices/finalizers
      - entandocompositeapps
      - entandocompositeapps/finalizers
      - entandodebundles
      - entandodebundles/finalizers
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
---
# Source: preview/charts/operator/templates/operator-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-operator
  namespace: flex
rules:
  - apiGroups:
      - entando.org
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
    verbs:
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get

---
# Source: preview/charts/operator/templates/plugin-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-plugin
  namespace: flex
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandoplugins
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update

---
# Source: preview/charts/operator/templates/k8s-service-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-k8s-service-rolebinding
  namespace: flex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-k8s-service
subjects:
  - kind: ServiceAccount
    name: entando-k8s-service
    namespace: flex

---
# Source: preview/charts/operator/templates/operator-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-operator-rolebinding
  namespace: flex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-operator
subjects:
  - kind: ServiceAccount
    name: entando-operator
    namespace: flex
---
# Source: preview/charts/operator/templates/plugin-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-plugin-rolebinding
  namespace: flex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-plugin
subjects:
  - kind: ServiceAccount
    name: entando-plugin
    namespace: flex

---
# Source: preview/charts/operator/templates/deployment.yaml

apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: quickstart-operator
  namespace: flex
  labels:
    draft: draft-app
    chart: "operator-6.2.5"
spec:
  replicas: 1
  selector:
    matchLabels:
      draft: draft-app
      app: quickstart-operator
  template:
    metadata:
      labels:
        draft: draft-app
        app: quickstart-operator
    spec:
      serviceAccountName: entando-operator
      volumes:
      containers:
        - name: operator
          image: "docker.io/entando/entando-k8s-controller-coordinator:6.2.5"
          imagePullPolicy: Always
          volumeMounts:
          env:
            - name: ENTANDO_K8S_OPERATOR_SERVICEACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: ENTANDO_DEFAULT_ROUTING_SUFFIX
              value: "apps.rd.entando.org"
            - name: ENTANDO_DISABLE_KEYCLOAK_SSL_REQUIREMENT
              value: "true"
            - name: ENTANDO_DOCKER_IMAGE_ORG_FALLBACK
              value: "entando"
            - name: ENTANDO_DOCKER_IMAGE_VERSION_FALLBACK
              value: "6.0.0"
            - name: ENTANDO_DOCKER_REGISTRY_FALLBACK
              value: "docker.io"
            - name: ENTANDO_K8S_OPERATOR_FORCE_DB_PASSWORD_RESET
              value: "true"
            - name: ENTANDO_K8S_OPERATOR_IMPOSE_DEFAULT_LIMITS
              value: "false"
            - name: ENTANDO_K8S_OPERATOR_SECURITY_MODE
              value: "lenient"
            - name: ENTANDO_POD_COMPLETION_TIMEOUT_SECONDS
              value: "1000"
            - name: ENTANDO_POD_READINESS_TIMEOUT_SECONDS
              value: "1000"
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/EntandoControllerCoordinator.ready
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/EntandoControllerCoordinator.ready
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 512Mi
          terminationGracePeriodSeconds:

---
# Source: preview/templates/entando-composite-app.yaml
kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "quickstart-composite-app"
  namespace: flex
entandoStatus:
  serverStatuses: {}
  entandoDeploymentPhase: "requested"
spec:
  components:
    - kind: "EntandoKeycloakServer"
      metadata:
        name: "quickstart-kc"
      spec:
        dbms: none
        isDefault: true
        replicas: 1
    - kind: "EntandoClusterInfrastructure"
      metadata:
        name: "quickstart-eci"
      spec:
        dbms: none
        replicas: 1
        isDefault: true
    - kind: "EntandoApp"
      metadata:
        annotations: {}
        labels: {}
        name: "quickstart"
      spec:
        dbms: none
        replicas: 1
        standardServerImage: wildfly
        ingressPath: /entando-de-app
        parameters:
          SPRING_PROFILES_ACTIVE: "default,swagger"
    - kind: "EntandoPlugin"
      metadata:
        name: "std-demo-customer"
      spec:
        image: "docker.io/jwhite101/customer:0.0.10"
        replicas: 1
        dbms: none
        roles:
          - name: "customer-list"
            code: "customer-list"
        permissions:
          - clientId: realm-management
            role: manage-users
          - clientId: realm-management
            role: view-users
        parameters: {}
        ingressPath: "/customer"
        healthCheckPath: "/management/health"
        securityLevel: lenient
        connectionConfigNames: []
    - kind: "EntandoAppPluginLink"
      metadata:
        name: "std-demo-customer-apl"
      spec:
        entandoAppNamespace: "flex"
        entandoAppName: "quickstart"
        entandoPluginNamespace: "flex"
        entandoPluginName: "std-demo-customer"
    - kind: "EntandoPlugin"
      metadata:
        name: "standard-demo-banking"
      spec:
        image: "docker.io/jwhite101/banking:0.0.18"
        replicas: 1
        dbms: none
        roles:
          - name: "task-list"
            code: "task-list"
        permissions: []
        parameters: {}
        ingressPath: "/banking"
        healthCheckPath: "/management/health"
        securityLevel: lenient
        connectionConfigNames: []
    - kind: "EntandoAppPluginLink"
      metadata:
        name: "standard-demo-banking-apl"
      spec:
        entandoAppNamespace: "flex"
        entandoAppName: "quickstart"
        entandoPluginNamespace: "flex"
        entandoPluginName: "standard-demo-banking"

---
# Source: preview/templates/db-admin-secret.yaml
