INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',0,'Brand-Logo',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',2,'Login_buttons',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',13,'seedscard-transaction-table',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('credit_card',0,'Brand-Logo',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('sign_up',2,'Login_buttons',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('credit_card',2,'Login_buttons',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('sign_up',4,'signup',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',4,'seeds_card','<?xml version="1.0" encoding="UTF-8"?><properties><property key="cardname">checking</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('credit_card',4,'apply_form_banner',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('credit_card',5,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR80</property><property key="modelId">8</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('credit_card',6,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR85</property><property key="modelId">7</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('credit_card',7,'credit_card_user_apply_form',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('credit_card',12,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',0,'back_to_seed',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',1,'search_form',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',2,'language_choose',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',3,'brand_insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',6,'Breadcrumb',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',14,'footer-insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('manage_users',0,'Brand-Logo',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('manage_users',2,'Login_buttons',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('manage_users',5,'manage_users',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('sign_up',0,'Brand-Logo',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',0,'Brand-Logo',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',7,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR144</property><property key="modelId">11</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',6,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR147</property><property key="modelId">10</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',9,'find-atm',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',13,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',5,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR164</property><property key="modelId">8</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',10,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR102</property><property key="modelId">8</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',2,'Login_buttons',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',0,'back_to_seed',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',4,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR149</property><property key="modelId">9</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('interest',8,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">BNR140</property><property key="modelId">12</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',1,'search_form',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',2,'language_choose',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',3,'brand_insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',5,'insurance_login',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',6,'Breadcrumb',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',9,'content_viewer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',14,'footer-insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',7,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">MPC608</property><property key="modelId">100</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',8,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">MPC606</property><property key="modelId">101</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',9,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">MPC596</property><property key="modelId">102</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',0,'back_to_seed',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',1,'search_form',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',2,'language_choose',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',3,'brand_insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',6,'Breadcrumb',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',14,'footer-insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',7,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">PRD662</property><property key="modelId">109</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',4,'entando-widget-navigation_bar','<?xml version="1.0" encoding="UTF-8"?><properties><property key="navSpec">code(seed_insurances) + code(products) + code(my_portal)</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',0,'back_to_seed',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',1,'search_form',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',2,'language_choose',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',3,'brand_insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',5,'insurance_login',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',6,'Breadcrumb',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',14,'footer-insurance',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',9,'content_viewer_list','<?xml version="1.0" encoding="UTF-8"?><properties><property key="maxElemForItem">3</property><property key="title_it">Prodotti Seed Insurance</property><property key="userFilters">(attributeFilter=false;key=category;categoryCode=products)+(attributeFilter=true;key=title)</property><property key="filters">(order=DESC;attributeFilter=false;key=modified)</property><property key="title_en">Seed Insurance Product</property><property key="contentType">PRD</property><property key="modelId">107</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',10,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">MPC616</property><property key="modelId">104</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',5,'insurance_login',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',4,'entando-widget-navigation_bar','<?xml version="1.0" encoding="UTF-8"?><properties><property key="navSpec">code(seed_insurances) + code(products) + code(my_portal)</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',4,'entando-widget-navigation_bar','<?xml version="1.0" encoding="UTF-8"?><properties><property key="navSpec">code(seed_insurances) + code(products) + code(my_portal)</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('product_details',4,'entando-widget-navigation_bar','<?xml version="1.0" encoding="UTF-8"?><properties><property key="navSpec">code(seed_insurances) + code(products) + code(my_portal)</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',7,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">MPC614</property><property key="modelId">101</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',9,'content_viewer_list','<?xml version="1.0" encoding="UTF-8"?><properties><property key="maxElemForItem">3</property><property key="title_it">I miei prodotti</property><property key="userFilters">(attributeFilter=false;key=category;categoryCode=products)</property><property key="categories">my_product</property><property key="filters">(order=DESC;attributeFilter=false;key=modified)</property><property key="title_en">My Products</property><property key="contentType">PRD</property><property key="modelId">107</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',6,'seeds_card','<?xml version="1.0" encoding="UTF-8"?><properties><property key="cardname">creditcard</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',0,'Brand-Logo',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',2,'Login_buttons',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',4,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentDescription">main-banner</property><property key="modelId">1</property><property key="contentId">BNR37</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',5,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentDescription">banner light green</property><property key="modelId">2</property><property key="contentId">BNR34</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',6,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentDescription">Banner with inner card</property><property key="modelId">3</property><property key="contentId">BNR31</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',7,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentDescription">Banner with accordion</property><property key="modelId">4</property><property key="contentId">BNR16</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',8,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentDescription">Banner with dark green background</property><property key="modelId">5</property><property key="contentId">BNR28</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',9,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentDescription">Banner with white background</property><property key="modelId">6</property><property key="contentId">BNR19</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('homepage',13,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',10,'content_viewer','<?xml version="1.0" encoding="UTF-8"?><properties><property key="contentId">MPC611</property><property key="modelId">104</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('my_portal',11,'content_viewer_list','<?xml version="1.0" encoding="UTF-8"?><properties><property key="maxElemForItem">3</property><property key="title_it">Servizio Clienti</property><property key="categories">customer_service</property><property key="filters">(attributeFilter=false;order=DESC;key=modified)</property><property key="title_en">Customer Service</property><property key="contentType">MPC</property><property key="modelId">103</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('seed_insurances',10,'content_viewer_list','<?xml version="1.0" encoding="UTF-8"?><properties><property key="maxElemForItem">3</property><property key="title_it">Perchè Seed Assicurazioni</property><property key="categories">benefits</property><property key="filters">(attributeFilter=false;order=DESC;key=modified)</property><property key="title_en">Why Seed Insurance</property><property key="contentType">MPC</property><property key="modelId">103</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('products',5,'insurance_login',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',11,'list_item','<?xml version="1.0" encoding="UTF-8"?><properties><property key="count">0</property><property key="icon">viewstatements</property><property key="title">View Statements</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('test',6,'seeds_card','<?xml version="1.0" encoding="UTF-8"?><properties><property key="cardname">creditcard</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',5,'seeds_card_ng','<?xml version="1.0" encoding="UTF-8"?><properties><property key="cardname">savings</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('dashboard',7,'list_item','<?xml version="1.0" encoding="UTF-8"?><properties><property key="count">0</property><property key="icon">managealerts</property><property key="title">Alerts</property></properties>');
