INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD673','title','Seed International Travel',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD673','title','Seed International Travel',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD670','title','Seed Home',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD670','title','Seed Home',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD666','title','Seed Bikes',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD666','title','Seed Bikes',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD662','title','Seed International Travel and Medical Insurance',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD662','title','Seed International Travel and Medical Insurance',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD659','title','Seed Life Family',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD659','title','Seed Life Family',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD656','title','Seed Car',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD656','title','Seed Car',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD653','title','Seed Home and Contents',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRD653','title','Seed Home and Contents',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS628','title','Debt relief for poorest countries could extend beyond 2020',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS628','title','Debt relief for poorest countries could extend beyond 2020',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS631','title','Do debt funds still have a place in an investor’s portfolio?',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS631','title','Do debt funds still have a place in an investor’s portfolio?',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS634','title','Employees are moving into ergonomic home-work setups',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS634','title','Employees are moving into ergonomic home-work setups',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS638','title','Manufacturers Respond to Coronavirus',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS638','title','Manufacturers Respond to Coronavirus',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS641','title','How to tackle financial stress',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS641','title','How to tackle financial stress',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS650','title','Dealing with a financial emergency',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS650','title','Dealing with a financial emergency',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS644','title','Emergency cash: What are your options?',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS644','title','Emergency cash: What are your options?',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS647','title','Fraud and Cyber Security Systems',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS647','title','Fraud and Cyber Security Systems',NULL,NULL,'it');
