name: Application CI
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Run backend test
        run: |
          cd "$GITHUB_WORKSPACE/banking-plugin"
          chmod +x mvnw
          ./mvnw -ntp clean verify
      - name: Package application
        run: |
          cd "$GITHUB_WORKSPACE/banking-plugin"
          ./mvnw -ntp package -Pprod -DskipTests
  micro-frontends:
    name: ${{ matrix.widget }} micro frontend
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        widget: [ alert-bar-icon-react, dashboard-card-angular ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.15.0'
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/banking-plugin/ui/widgets/banking-widgets/${{ matrix.widget }}"
          npm install
          npm test
